node {
  def app

  stage('clear work space'){
    cleanWs()
  }
  stage('clone repo') {
    git credentialsId: 'githgallo', url: 'https://github.com/hgallo0/cf-dc.git'
  }
  stage ('Build') {
    dir('./cf-hello') {
         sh './gradlew distZip' 
    }
  }
  stage('Results') {
      archive 'target/*.jar'
  }
  stage('UPload to Nexus') {
    dir('./cf-hello/') {
    nexusArtifactUploader artifacts: [[artifactId: 'dc', classifier: 'stage', file: 'target/*.jar', type: 'jar']], credentialsId: 'nexus', groupId: 'nexus', nexusUrl: '10.100.11.164:8081', nexusVersion: 'nexus3', protocol: 'http', repository: 'hgallotest', version: '1.0.0'
    }
  }
}
